logging:
  level:
    tech.guicam: trace
spring:
  datasource:
    username: root
    password: Inpt@2025
    url: jdbc:mysql://localhost:3306/db_soins_santes
  jpa:
    show-sql: true

sql:
  init:
    mode: always